CREATE TABLE problems (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_id INTEGER
        REFERENCES locations(id) ON DELETE CASCADE NOT NULL,
    problem_name TEXT NOT NULL,
    grade TEXT NOT NULL,
    area TEXT,
    notes TEXT,
    sent BOOLEAN
);